name: hello-world
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: hello-from-bash
        run: echo "Hello from Bash!"
      - name: hello-from-R
        uses: actions/checkout@v3
        uses: r-lib/actions/setup-r@v2
          with:
            r-version: '3.5.3'
        run: Rscript -e 'print("Hello from R!")'
